services:
  - type: web
    plan: free
    name: qr-viewer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run view_media.py --server.address=0.0.0.0 --server.port=$PORT --server.enableXsrfProtection=false"
    healthCheckPath: /
